import type { VxeGridPropTypes, VxeGridProps } from 'vxe-table/types/grid';
import apiService from '@/api-service/index';
import { useI18n } from '@/hooks/web/useI18n';

const viewPermissionService = apiService.system.viewPermissionService;

// begcode-please-regenerate-this-file 如果您不希望重新生成代码时被覆盖，将please修改为don't ！！！-->

const searchForm = (relationshipApis): any[] => {
  const { getEnumDict } = useI18n();
  return [
    {
      title: 'ID',
      field: 'id',
      componentType: 'Text',
      value: '',
      type: 'Long',
      operator: '',
      span: 8,
      componentProps: {},
    },
    {
      title: '权限名称',
      field: 'text',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      componentProps: {},
    },
    {
      title: '权限类型',
      field: 'type',
      componentType: 'Select',
      value: '',
      span: 8,
      operator: 'equals',
      type: 'Enum',
      componentProps: () => {
        return { options: getEnumDict('ViewPermissionType'), style: 'width: 100%' };
      },
    },
    {
      title: '多语言Key',
      field: 'localeKey',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: '显示分组名',
      field: 'group',
      componentType: 'RadioGroup',
      value: '',
      operator: '',
      span: 8,
      hidden: true,
      type: 'Boolean',
      componentProps: {
        optionType: 'button',
        buttonStyle: 'solid',
        options: [
          { label: '是', value: true },
          { label: '否', value: false },
        ],
      },
    },
    {
      title: '路由',
      field: 'link',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: '外部链接',
      field: 'externalLink',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: '链接目标',
      field: 'target',
      componentType: 'Select',
      value: '',
      span: 8,
      hidden: true,
      operator: 'equals',
      type: 'Enum',
      componentProps: () => {
        return { options: getEnumDict('TargetType'), style: 'width: 100%' };
      },
    },
    {
      title: '禁用菜单',
      field: 'disabled',
      componentType: 'RadioGroup',
      value: '',
      operator: '',
      span: 8,
      hidden: true,
      type: 'Boolean',
      componentProps: {
        optionType: 'button',
        buttonStyle: 'solid',
        options: [
          { label: '是', value: true },
          { label: '否', value: false },
        ],
      },
    },
    {
      title: '隐藏菜单',
      field: 'hide',
      componentType: 'RadioGroup',
      value: '',
      operator: '',
      span: 8,
      hidden: true,
      type: 'Boolean',
      componentProps: {
        optionType: 'button',
        buttonStyle: 'solid',
        options: [
          { label: '是', value: true },
          { label: '否', value: false },
        ],
      },
    },
    {
      title: '隐藏面包屑',
      field: 'hideInBreadcrumb',
      componentType: 'RadioGroup',
      value: '',
      operator: '',
      span: 8,
      hidden: true,
      type: 'Boolean',
      componentProps: {
        optionType: 'button',
        buttonStyle: 'solid',
        options: [
          { label: '是', value: true },
          { label: '否', value: false },
        ],
      },
    },
    {
      title: '快捷菜单项',
      field: 'shortcut',
      componentType: 'RadioGroup',
      value: '',
      operator: '',
      span: 8,
      hidden: true,
      type: 'Boolean',
      componentProps: {
        optionType: 'button',
        buttonStyle: 'solid',
        options: [
          { label: '是', value: true },
          { label: '否', value: false },
        ],
      },
    },
    {
      title: '菜单根节点',
      field: 'shortcutRoot',
      componentType: 'RadioGroup',
      value: '',
      operator: '',
      span: 8,
      hidden: true,
      type: 'Boolean',
      componentProps: {
        optionType: 'button',
        buttonStyle: 'solid',
        options: [
          { label: '是', value: true },
          { label: '否', value: false },
        ],
      },
    },
    {
      title: '允许复用',
      field: 'reuse',
      componentType: 'RadioGroup',
      value: '',
      operator: '',
      span: 8,
      hidden: true,
      type: 'Boolean',
      componentProps: {
        optionType: 'button',
        buttonStyle: 'solid',
        options: [
          { label: '是', value: true },
          { label: '否', value: false },
        ],
      },
    },
    {
      title: '权限代码',
      field: 'code',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: '权限描述',
      field: 'description',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: '排序',
      field: 'order',
      componentType: 'Text',
      value: '',
      type: 'Integer',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: 'api权限标识串',
      field: 'apiPermissionCodes',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: '组件名称',
      field: 'componentFile',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: '重定向路径',
      field: 'redirect',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      hidden: true,
      componentProps: {},
    },
    {
      title: '子节点',
      field: 'children',
      componentType: 'ApiSelect',
      value: '',
      operator: '',
      span: 8,
      componentProps: { api: relationshipApis.children, style: 'width: 100%', valueField: 'id', labelField: 'text' },
    },
    {
      title: '上级',
      field: 'parent',
      componentType: 'ApiSelect',
      value: '',
      operator: '',
      span: 8,
      componentProps: { api: relationshipApis.parent, style: 'width: 100%', valueField: 'id', labelField: 'text' },
    },
  ];
};

const columns = (): VxeGridPropTypes.Columns => {
  const { getEnumDict } = useI18n();
  return [
    {
      fixed: 'left',
      type: 'checkbox',
      width: 60,
    },
    {
      title: 'ID',
      field: 'id',
      minWidth: 80,
      visible: false,
      treeNode: false,
      params: { type: 'LONG' },
    },
    {
      title: '权限名称',
      field: 'text',
      minWidth: 160,
      visible: true,
      treeNode: true,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '权限类型',
      field: 'type',
      minWidth: 100,
      visible: true,
      treeNode: false,
      params: { type: 'ENUM' },
      formatter: ({ cellValue }) => {
        return (getEnumDict('ViewPermissionType').find(item => item.value === cellValue) || { label: cellValue }).label;
      },
      editRender: { name: 'ASelect', props: { options: getEnumDict('ViewPermissionType') }, enabled: false },
    },
    {
      title: '多语言Key',
      field: 'localeKey',
      minWidth: 160,
      visible: false,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '显示分组名',
      field: 'group',
      minWidth: 70,
      visible: true,
      treeNode: false,
      params: { type: 'BOOLEAN' },
      cellRender: { name: 'ASwitch', props: { disabled: true } },
    },
    {
      title: '路由',
      field: 'link',
      minWidth: 160,
      visible: true,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '外部链接',
      field: 'externalLink',
      minWidth: 160,
      visible: true,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '链接目标',
      field: 'target',
      minWidth: 100,
      visible: true,
      treeNode: false,
      params: { type: 'ENUM' },
      formatter: ({ cellValue }) => {
        return (getEnumDict('TargetType').find(item => item.value === cellValue) || { label: cellValue }).label;
      },
      editRender: { name: 'ASelect', props: { options: getEnumDict('TargetType') }, enabled: false },
    },
    {
      title: '图标',
      field: 'icon',
      minWidth: 50,
      visible: true,
      treeNode: false,
      params: { type: 'STRING' },
      cellRender: { name: 'AIcon', props: { disabled: false, size: 18 } },
    },
    {
      title: '禁用菜单',
      field: 'disabled',
      minWidth: 70,
      visible: true,
      treeNode: false,
      params: { type: 'BOOLEAN' },
      cellRender: { name: 'ASwitch', props: { disabled: true } },
    },
    {
      title: '隐藏菜单',
      field: 'hide',
      minWidth: 70,
      visible: true,
      treeNode: false,
      params: { type: 'BOOLEAN' },
      cellRender: { name: 'ASwitch', props: { disabled: true } },
    },
    {
      title: '隐藏面包屑',
      field: 'hideInBreadcrumb',
      minWidth: 70,
      visible: true,
      treeNode: false,
      params: { type: 'BOOLEAN' },
      cellRender: { name: 'ASwitch', props: { disabled: true } },
    },
    {
      title: '快捷菜单项',
      field: 'shortcut',
      minWidth: 70,
      visible: true,
      treeNode: false,
      params: { type: 'BOOLEAN' },
      cellRender: { name: 'ASwitch', props: { disabled: true } },
    },
    {
      title: '菜单根节点',
      field: 'shortcutRoot',
      minWidth: 70,
      visible: true,
      treeNode: false,
      params: { type: 'BOOLEAN' },
      cellRender: { name: 'ASwitch', props: { disabled: true } },
    },
    {
      title: '允许复用',
      field: 'reuse',
      minWidth: 70,
      visible: false,
      treeNode: false,
      params: { type: 'BOOLEAN' },
      cellRender: { name: 'ASwitch', props: { disabled: true } },
    },
    {
      title: '权限代码',
      field: 'code',
      minWidth: 160,
      visible: true,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '权限描述',
      field: 'description',
      minWidth: 160,
      visible: false,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '排序',
      field: 'order',
      minWidth: 50,
      visible: true,
      treeNode: false,
      params: { type: 'INTEGER' },
      sortable: true,
    },
    {
      title: 'api权限标识串',
      field: 'apiPermissionCodes',
      minWidth: 160,
      visible: false,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '组件名称',
      field: 'componentFile',
      minWidth: 160,
      visible: true,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '重定向路径',
      field: 'redirect',
      minWidth: 160,
      visible: true,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '操作',
      field: 'recordOperation',
      fixed: 'right',
      headerAlign: 'center',
      align: 'right',
      showOverflow: false,
      width: 120,
      slots: { default: 'recordAction' },
    },
  ];
};

const baseGridOptions = (ajax, toolbarButtons, toolbarTools): VxeGridProps => {
  return {
    rowConfig: {
      keyField: 'id',
      isHover: true,
    },
    loading: undefined,
    border: true,
    showHeaderOverflow: true,
    showOverflow: true,
    keepSource: true,
    id: 'vxe_grid_view_permission',
    height: 600,
    printConfig: {
      columns: [
        // { field: 'name' },
      ],
    },
    filterConfig: {
      remote: true,
    },
    columnConfig: {
      resizable: true,
    },
    sortConfig: {
      trigger: 'cell',
      remote: true,
      orders: ['asc', 'desc', null],
      multiple: true,
      showIcon: true,
      defaultSort: {
        field: 'order',
        order: 'asc',
      },
    },
    pagerConfig: {
      layouts: ['Sizes', 'PrevJump', 'PrevPage', 'Number', 'NextPage', 'NextJump', 'FullJump', 'Total'],
      pageSize: 15,
      pageSizes: [5, 10, 15, 20, 30, 50],
      total: 0,
      pagerCount: 5,
      currentPage: 1,
      autoHidden: false,
      slots: {
        left: 'pagerLeft',
      },
    },
    importConfig: {
      remote: true,
      importMethod: ajax.import,
    },
    exportConfig: {
      columnFilterMethod: ({ column }) => ['radio', 'checkbox'].includes(column.type),
    },
    checkboxConfig: {
      // labelField: 'id',
      reserve: true,
      highlight: true,
    },
    editRules: {},
    editConfig: {
      trigger: 'click',
      mode: 'cell',
      showStatus: true,
    },
    customConfig: {
      storage: {
        visible: true,
        resizable: false,
        sort: true,
        fixed: true,
      },
    },
    proxyConfig: {
      enabled: true,
      autoLoad: true,
      seq: true,
      sort: true,
      filter: true,
      response: {
        result: 'records',
        total: 'total',
      },
      ajax,
    },
    toolbarConfig: {
      custom: false,
      import: false,
      print: false,
      export: false,
      slots: {
        buttons: 'toolbar_buttons',
      },
      buttons: toolbarButtons,
      tools: toolbarTools,
    },
    treeConfig: {
      childrenField: 'children',
      indent: 20,
      showLine: false,
      expandAll: false,
      accordion: false,
      trigger: 'default',
    },
  };
};

const ListProps = {
  query: {
    type: Object,
    default: () => ({}),
  },
  editIn: {
    ype: String,
    default: 'page',
  },
  baseData: {
    type: Object,
    default: () => ({}),
  },
  cardSlots: {
    type: Array,
    default: ['title', 'rightExtra'],
  },
  cardExtra: {
    type: Array,
    default: ['import', 'export', 'print'],
  },
  gridOptions: {
    type: Object,
    default: () => ({}),
  },
  selectType: {
    type: String,
    default: 'checkbox', // checkbox/radio/none/seq
  },
  searchFormOptions: {
    type: Object,
    default: () => ({
      disabled: false,
    }),
  },
  gridCustomConfig: {
    type: Object,
    default: () => ({
      hideOperations: false,
      hideSlots: [],
      hideColumns: [],
    }),
  },
  parentContainer: {
    type: String,
    default: '',
  },
};

export default {
  searchForm,
  columns,
  baseGridOptions,
  ListProps,
};
