import type { VxeGridPropTypes, VxeGridProps } from 'vxe-table/types/grid';
import apiService from '@/api-service/index';

const authorityService = apiService.system.authorityService;
const relationshipApis: any = {
  children: apiService.system.authorityService.tree,
  viewPermissions: apiService.system.viewPermissionService.tree,
  apiPermissions: apiService.system.apiPermissionService.tree,
  parent: apiService.system.authorityService.tree,
  users: apiService.system.userService.retrieve,
  department: apiService.settings.departmentService.tree,
};

// begcode-please-regenerate-this-file 如果您不希望重新生成代码时被覆盖，将please修改为don't ！！！-->

const searchForm = (): any[] => {
  return [
    {
      title: 'ID',
      field: 'id',
      componentType: 'Text',
      value: '',
      type: 'Long',
      operator: '',
      span: 8,
      componentProps: {},
    },
    {
      title: '角色名称',
      field: 'name',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      componentProps: {},
    },
    {
      title: '角色代号',
      field: 'code',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      componentProps: {},
    },
    {
      title: '信息',
      field: 'info',
      componentType: 'Text',
      value: '',
      type: 'String',
      operator: '',
      span: 8,
      componentProps: {},
    },
    {
      title: '排序',
      field: 'order',
      componentType: 'Text',
      value: '',
      type: 'Integer',
      operator: '',
      span: 8,
      componentProps: {},
    },
    {
      title: '展示',
      field: 'display',
      componentType: 'RadioGroup',
      value: '',
      operator: '',
      span: 8,
      type: 'Boolean',
      componentProps: {
        optionType: 'button',
        buttonStyle: 'solid',
        options: [
          { label: '是', value: true },
          { label: '否', value: false },
        ],
      },
    },
    {
      title: '子节点',
      field: 'children',
      componentType: 'ApiSelect',
      value: '',
      operator: '',
      span: 8,
      componentProps: { api: relationshipApis.children, style: 'width: 100%', valueField: 'id', labelField: 'name' },
    },
    {
      title: '菜单列表',
      field: 'viewPermissions',
      componentType: 'ApiSelect',
      value: '',
      operator: '',
      span: 8,
      componentProps: { api: relationshipApis.viewPermissions, style: 'width: 100%', valueField: 'id', labelField: 'text' },
    },
    {
      title: 'Api权限列表',
      field: 'apiPermissions',
      componentType: 'ApiSelect',
      value: '',
      operator: '',
      span: 8,
      componentProps: { api: relationshipApis.apiPermissions, style: 'width: 100%', valueField: 'id', labelField: 'name' },
    },
    {
      title: '上级',
      field: 'parent',
      componentType: 'ApiSelect',
      value: '',
      operator: '',
      span: 8,
      componentProps: { api: relationshipApis.parent, style: 'width: 100%', valueField: 'id', labelField: 'name' },
    },
    {
      title: '用户列表',
      field: 'users',
      componentType: 'ApiSelect',
      value: '',
      operator: '',
      span: 8,
      componentProps: { api: relationshipApis.users, style: 'width: 100%', valueField: 'id', labelField: 'firstName' },
    },
  ];
};

const columns = (): VxeGridPropTypes.Columns => {
  return [
    {
      fixed: 'left',
      type: 'checkbox',
      width: 60,
    },
    {
      title: 'ID',
      field: 'id',
      minWidth: 80,
      visible: false,
      treeNode: false,
      params: { type: 'LONG' },
      editRender: { name: 'AInputNumber', enabled: false, props: { controls: false } },
    },
    {
      title: '角色名称',
      field: 'name',
      minWidth: 160,
      visible: true,
      treeNode: true,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '角色代号',
      field: 'code',
      minWidth: 160,
      visible: true,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '信息',
      field: 'info',
      minWidth: 160,
      visible: true,
      treeNode: false,
      params: { type: 'STRING' },
      editRender: { name: 'AInput', enabled: false },
    },
    {
      title: '排序',
      field: 'order',
      minWidth: 80,
      visible: true,
      treeNode: false,
      params: { type: 'INTEGER' },
      titlePrefix: { icon: 'vxe-icon-sort', content: '排序操作列' },
      editRender: { name: 'ADragSort', enabled: false, props: { remoteApi: authorityService.updateSortValue } },
    },
    {
      title: '展示',
      field: 'display',
      minWidth: 70,
      visible: true,
      treeNode: false,
      params: { type: 'BOOLEAN' },
      cellRender: { name: 'ASwitch', props: { disabled: false } },
    },
    {
      title: '菜单列表',
      field: 'viewPermissions',
      minWidth: 120,
      editRender: {
        name: 'ASelectModal',
        enabled: true,
        props: {
          showComponentName: 'TreeSelect',
          api: relationshipApis.viewPermissions,
          container: 'drawer',
          labelInValue: true,
          componentName: 'ApiTree',
          multiple: true,
          avatarSlotName: 'default',
          avatarSlotField: 'text',
          avatarTipField: 'text',
          checkStrictly: true,
          fieldNames: { label: 'text', value: 'id', children: 'children' },
          style: { width: '100%' },
        },
      },
    },
    {
      title: 'Api权限列表',
      field: 'apiPermissions',
      minWidth: 120,
      editRender: {
        name: 'ASelectModal',
        enabled: true,
        props: {
          showComponentName: 'TreeSelect',
          api: relationshipApis.apiPermissions,
          container: 'drawer',
          labelInValue: true,
          componentName: 'ApiTree',
          multiple: true,
          avatarSlotName: 'default',
          avatarSlotField: 'name',
          avatarTipField: 'name',
          checkStrictly: true,
          fieldNames: { label: 'name', value: 'id', children: 'children' },
          style: { width: '100%' },
        },
      },
    },
    {
      title: '用户列表',
      field: 'users',
      minWidth: 120,
      editRender: {
        name: 'ASelectModal',
        enabled: false,
        props: {
          showComponentName: 'Select',
          container: 'modal',
          componentName: 'UserRelation',
          multiple: true,
          style: { width: '100%' },
          queryNames: ['authoritiesId'],
          avatarSlotName: 'default',
          avatarSlotField: 'firstName',
          avatarTipField: 'firstName',
          rowIdField: 'row.id',
          source: 'Authority',
        },
      },
    },
    {
      title: '操作',
      field: 'operation',
      fixed: 'right',
      headerAlign: 'center',
      align: 'right',
      showOverflow: false,
      width: 170,
      slots: { default: 'recordAction' },
    },
  ];
};

const baseGridOptions = (): VxeGridProps => {
  return {
    rowConfig: {
      keyField: 'id',
      isHover: true,
    },
    border: true,
    showHeaderOverflow: true,
    showOverflow: true,
    keepSource: true,
    id: 'full_edit_1',
    height: 600,
    printConfig: {
      columns: [
        // { field: 'name' },
      ],
    },
    filterConfig: {
      remote: true,
    },
    columnConfig: {
      resizable: true,
    },
    sortConfig: {
      trigger: 'cell',
      remote: true,
      orders: ['asc', 'desc', null],
      multiple: true,
      defaultSort: {
        field: 'id',
        order: 'desc',
      },
    },
    pagerConfig: {
      layouts: ['Sizes', 'PrevJump', 'PrevPage', 'Number', 'NextPage', 'NextJump', 'FullJump', 'Total'],
      pageSize: 15,
      pageSizes: [5, 10, 15, 20, 30, 50],
      total: 0,
      pagerCount: 5,
      currentPage: 1,
      autoHidden: true,
    },
    importConfig: {},
    exportConfig: {},
    checkboxConfig: {
      // labelField: 'id',
      reserve: true,
      highlight: true,
    },
    editRules: {},
    editConfig: {
      trigger: 'click',
      mode: 'cell',
      showStatus: true,
    },
    treeConfig: {
      childrenField: 'children',
      indent: 20,
      showLine: false,
      expandAll: false,
      accordion: false,
      trigger: 'default',
    },
  };
};

export default {
  searchForm,
  columns,
  baseGridOptions,
};
