package com.begcode.monolith.settings.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SiteConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteConfigAllPropertiesEquals(SiteConfig expected, SiteConfig actual) {
        assertSiteConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertSiteConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteConfigAllUpdatablePropertiesEquals(SiteConfig expected, SiteConfig actual) {
        assertSiteConfigUpdatableFieldsEquals(expected, actual);
        assertSiteConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteConfigAutoGeneratedPropertiesEquals(SiteConfig expected, SiteConfig actual) {
        assertThat(expected)
            .as("Verify SiteConfig auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteConfigUpdatableFieldsEquals(SiteConfig expected, SiteConfig actual) {
        assertThat(expected)
            .as("Verify SiteConfig relevant properties")
            .satisfies(e -> assertThat(e.getCategoryName()).as("check categoryName").isEqualTo(actual.getCategoryName()))
            .satisfies(e -> assertThat(e.getCategoryKey()).as("check categoryKey").isEqualTo(actual.getCategoryKey()))
            .satisfies(e -> assertThat(e.getDisabled()).as("check disabled").isEqualTo(actual.getDisabled()))
            .satisfies(e -> assertThat(e.getSortValue()).as("check sortValue").isEqualTo(actual.getSortValue()))
            .satisfies(e -> assertThat(e.getBuiltIn()).as("check builtIn").isEqualTo(actual.getBuiltIn()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteConfigUpdatableRelationshipsEquals(SiteConfig expected, SiteConfig actual) {}
}
